name: flutter_serve_app
description: A Flutter app that turns your phone into a simple server to serve photos and videos via hotspot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  shelf_static: ^1.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_manager: ^3.0.0
  http: ^1.1.0
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  android_intent_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

